services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-compiler-dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - pip-cache:/root/.local
    working_dir: /app
    command: bash


  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-compiler-test
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    command: pytest -s ./tests
    depends_on:
      - dev

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-compiler-prod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - pip-cache:/root/.local
    working_dir: /app
    command: >
      bash -c "chmod +x scripts/run_tac_gen.sh &&
          python3 src/ide/tac_server.py input.cps
          --port 8000
          --watch"
volumes:
  pip-cache:
